set linesize 300 ; 
set pagesize 300 ;

col USERNAME for a30;
col ACCOUNT_STATUS for a40;
col LAST_LOGIN for a30;
col PROFILE for a20;
col lock_date for a40;
col LAST_LOGIN for a45;


PROMPT DEFAULT SCHEMA DETAILS 
SELECT USERNAME, PROFILE, ACCOUNT_STATUS, LOCK_DATE, EXPIRY_DATE, CREATED, AUTHENTICATION_TYPE, LAST_LOGIN FROM DBA_USERS WHERE ORACLE_MAINTAINED='Y' order by ACCOUNT_STATUS;
SELECT ACCOUNT_STATUS,COUNT(*) FROM DBA_USERS WHERE ORACLE_MAINTAINED='Y' GROUP BY ACCOUNT_STATUS;
PROMPT

PROMPT NON-DEFAULT SCHEMAS 
SELECT USERNAME, PROFILE, ACCOUNT_STATUS, LOCK_DATE, EXPIRY_DATE, CREATED, AUTHENTICATION_TYPE, LAST_LOGIN FROM DBA_USERS WHERE ORACLE_MAINTAINED='N' order by ACCOUNT_STATUS;
SELECT ACCOUNT_STATUS,COUNT(*) FROM DBA_USERS WHERE ORACLE_MAINTAINED='N' GROUP BY ACCOUNT_STATUS;
